### ISSUE TITLE
Need to skip feed notifications

### ISSUE THREAD

**Issue by tripleee** [tripleee/sloshy#4]
The [VASP room was frozen](https://chat.stackexchange.com/transcript/message/58372735#58372735) even though Sloshy [thought it had recent activity.](https://chat.stackoverflow.com/transcript/message/52446032#52446032)

Apparently, the latest activity date should go back to the previous day with _non-feed_ activity.

**Comment by tripleee** [comment]
@ndattani Ping, hope this fixes the problem from last night.

**Comment by ndattani** [comment]
Thanks! Nice to see that we can look at SOBotics to find out Sloshy's nightly understanding of each tracked room's activity :)
