### ISSUE TITLE
Operations Research "general" chat room needs help staying open, but lacks response from diamond moderator team about permission to use Sloshy

### ISSUE THREAD

**Issue by ndattani** [tripleee/sloshy#45]
About this room: https://chat.stackexchange.com/rooms/94323/operations-research, I haven't heard from the site's diamond moderators since February, and even that was just a 1-word answer to something else. November 2022 was the last time I saw a diamond moderator actively "chatting" in that room.

I got JJJ (from Politics.SE) and Tyberius (from MMSE and Chem.SE) to unfreeze the room in March and April respectively, and Sloshy would help reduce the burden on such diamond moderators from ***other*** sites of the network. 

This is the "main" room on the site (General Discussion for or.stackexchange.com) , so it would seem to make sense that we keep the room open in favor of the "Linearizing a disjunctive expression into MILP" room that seems a lot more temporary (and seems to remain open only due to a bug in SE's chat code). I mentioned this the discussion about #44.

**Comment by tripleee** [comment]
I'll add it in the interim, but leave a notice to room owners to review the decision. Thanks for bringing it up again.

**Comment by tripleee** [comment]
@ndattani  I put you as the owner; if you don't have any objections, I'll go ahead and merge.

**Comment by tripleee** [comment]
Posted on the OR meta: https://or.meta.stackexchange.com/questions/379/should-a-bot-help-keep-the-or-chat-room-alive

**Comment by ndattani** [comment]
Thanks, I have no objections, and I've upvoted on your Meta question and answered it.

**Comment by tripleee** [comment]
A mod posted an answer which I interpret as approval for my proposal.
